version: "3.8"

services:
  app:
    container_name: "deno-self-monitoring"
    image: "hayd/alpine-deno:latest"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    env_file:
      - .env
    command: deno run --allow-all --watch --unstable app.js

  database:
    container_name: "postgres-database"
    image: "library/postgres:latest"
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:latest-alpine
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./sql/:/flyway/sql/
    command: -connectRetries=60 -baselineOnMigrate=true migrate
